### ISSUE TITLE
Documentation for portfolio items / pico-theme.yml

### ISSUE THREAD

**Issue by StuartJMackintosh** [mayamcdougall/freelancer-pico#1]
The index in this repo covers many features however doesn't seem to have anything on portfolio_items. They are mentioned in https://github.com/mayamcdougall/freelancer-pico/blob/main/pico-theme.yml although pico-theme itself isn't mentioned in the documentation.

**Comment by mayamcdougall** [comment]
Hey. 👋🏻

The `portfolio_items` you're seeing there are just some "demo data" for populating the gallery if you don't have any pages yet (or if you're using Pico's sample content).

You shouldn't have to touch `pico-theme.yml` at all, and that's why it's not mentioned anywhere.

Instead of have the site appear broken and empty on a new install, I decided with Freelancer to implement some demo content that way users could see what the experience would be like, without having to supply a full set of example markdown files.

Since Pico's sample content wouldn't really display anything useful in this theme, I recreated the original example content from [Start Bootstrap's demo](https://startbootstrap.com/theme/freelancer/), and hid it in `pico-theme.yml` with some clever coding.

At the start of `index.twig`, the theme checks to see if Pico's Pages array is empty, or if the index page seems like it's from Pico's sample contents, and if either of these things are true, it loads `config.theme_config.demo.portfolio_items` (eg, that bit in `pico-theme.yml`) as the data for the portfolio section instead.

That's all it is, just some hidden demo content.

There's nothing special you have to do to make your own portfolio items.  Any page that's not set as `Hidden` (via `Hidden: true` in its header) will appear in the gallery.

**Comment by mayamcdougall** [comment]
As a fun fact, when I was still developing it, my original implementation actually did require you to set `portfolio_item: true` in each page you wanted displayed in the gallery...

But then I realized that I was pretty much just doing the same thing as Pico's `Hidden` property, but in reverse.  So in the end it just made way more sense to respect `page.hidden` rather than having the user write `portfolio_item: true` in every file. 😂

**Comment by StuartJMackintosh** [comment]
Thanks Maya!

The theme is somewhat magic and that takes getting used to.

Could I suggest that the following is added: "You shouldn't have to touch pico-theme.yml at all, and that's why it's not mentioned anywhere." 
(unless it does already and I missed it...)

**Comment by mayamcdougall** [comment]
Maybe. 🤔

I didn't really thing it would be an issue, as it's not really a file you'd typically you'd touch.

Idk, our messaging on the `pico-theme.yml` part of the theme spec at the moment is a little, well, non-existent.  It was added for Pico 2.0, during a time when I was temporarily absent from the project.  The *intention* is that all themes need to include one, however, in practice very few do (either from being older than that or just unaware that they should have one).

It can technically also be used for theme level configuration, but afaik the only theme to actually do so is the Default Theme with its `widescreen` toggle.

I don't think most users (or developers) actually know this file exists. 😂 

So, in general I'd say it's not something I'd expect a user to touch unless they were explicitly told to do so.

Most themes should define their Metadata properties here (any non standard YAML items)\*, which would also mean a user could break their theme by incorrectly editing this file. 😒

So, to me it doesn't seem like a great place for user config anyway.  Maybe like, some hidden, last-resort override options that most users wouldn't need to touch, but that's about it.

@PhrozenByte Maybe there's a discussion to have there at some point? 🤔

\* Finally, you've probably noticed that Freelancer's configuration is all **lowercase**.  This is because I've used a lot of nested YAML options for configuration, while `pico-theme.yml` only supports registering a single, flat depth.

So that means I cheated and didn't "register" them in Pico.  That means it can only understand them when they're written "as-is" (lowercase, just like I've written them in my code), and they unfortunately don't get fancy uppercase aliases like most themes should have.

...But it was that or have a really cluttered `index.md` with all the options on a single level of indentation. 🤦🏻‍♀️

**Comment by PhrozenByte** [comment]
> So, to me it doesn't seem like a great place for user config anyway. Maybe like, some hidden, last-resort override options that most users wouldn't need to touch, but that's about it.
> 
> @PhrozenByte Maybe there's a discussion to have there at some point? thinking

`pico-theme.yml` isn't supposed to be a config file for users, but for theme devs. It can be used by theme devs to provide default configs though. Users can overwrite these in their `config.yml` (`my_config: true` in `pico-theme.yml` can be overwritten by `theme_config: { my_config: false }` in `config.yml`).

**Comment by mayamcdougall** [comment]
Ah, right, that makes more sense then.  I did think it was weird place for the `widescreen` option in the Default Theme, but since no one else has really ever used it for config... 🤷🏻‍♀️ 😂

**Comment by mayamcdougall** [comment]
@StuartJMackintosh FYI, a long-standing issue of ours is to get Pico's Documentation revised.  I've got an in-progress rewrite of things as well, aiming for a more digestible, less information-dense take on the subject.

It'll also hopefully be clearer about under-documented topics like this.

Maybe if/when your project reaches the point of onboarding a bunch of new Pico users, some of them might be interested in reviewing this work-in-progress effort and helping point out what works and what doesn't for new users.

Just a thought for the future though.

**Comment by mayamcdougall** [comment]
> Lack of reference in the docs does not mean the user will assume that it should not be touched, it is more often to assume that it is just not documented.

Ideally, Pico's documentation would be better.  The line involving `pico-theme.yml` though, is specifically weak, saying only:

> and a `pico-theme.yml` to set the necessary config parameters. Just refer to Pico’s default theme as an example.

It's a file that every theme is supposed to include, so it feels like a *Pico* problem, not a "put this in the readme of every theme" problem.

I don't necessarily agree that I should have to tell a user all the files *not* to touch.  I have a literal mountain of a readme, with installation and configuration instructions that are (hopefully) very clear and it's not mentioned anywhere in this.

Should I tell them not to be touching `index.twig`?  Not to mess with the javascript? Etc?

(Just being a little dramatic there to make my point, no malice intended. 😅)

So if the `.yml` extension on `pico-theme.yml` makes it too enticing to a user that might think it's for user configuration... maybe there's another problem here.  Maybe the issue is the way the repo is laid out.  I've purposely organized the repo so that if you wanted, you could `git clone` it into your themes folder.

In the past, I've used a mock folder layout, eg `themes/theme-name`, that keeps everything tucked away behind a folder for you to drag-and-drop, never thinking about the contents.  🤔

Idk, I'm torn on it either way.  Although this is definitely a paper cut... but I'm also not sure if it's really anything more than the growing pains of a new Pico user (sorry! 😓).  Everyone makes mistakes occasionally (and that's okay!), but I can't account for every possible mistake they could make.

And the idea that they could modify a file they weren't supposed to, and weren't told to modify... Idk. 🤷🏻‍♀️

**Comment by StuartJMackintosh** [comment]
Fair points - no argument with your approach. Lets leave this discussion here for others to see and understand. Will close.
